#!/bin/sh
set -e

RUNTIME_DIR="${STATS_DATA_DIR:-/app/runtime-data}"

mkdir -p "$RUNTIME_DIR"
chown -R nextjs:nodejs "$RUNTIME_DIR"
# Note: Dynamic JSON files are no longer seeded from public/data since they don't exist there.
# They will be generated by the backend when requested via the API.
echo "[entrypoint] Runtime directory prepared at $RUNTIME_DIR"

# Limit V8 heap to prevent unbounded growth on memory-constrained VMs.
# 192 MiB gives Next.js enough headroom to parse/persist the stats snapshot
# without repeatedly crashing under the 256 MiB container limit.
FRONTEND_NODE_OLD_SPACE_SIZE="${FRONTEND_NODE_OLD_SPACE_SIZE:-192}"
export NODE_OPTIONS="${NODE_OPTIONS:+$NODE_OPTIONS }--max-old-space-size=${FRONTEND_NODE_OLD_SPACE_SIZE}"

# Switch to nextjs user and run the server
exec su-exec nextjs:nodejs node server.js
