#!/bin/sh
set -e

RUNTIME_DIR="${STATS_DATA_DIR:-/app/runtime-data}"

mkdir -p "$RUNTIME_DIR"
chown -R nextjs:nodejs "$RUNTIME_DIR"
# Note: Dynamic JSON files are no longer seeded from public/data since they don't exist there.
# They will be generated by the backend when requested via the API.
echo "[entrypoint] Runtime directory prepared at $RUNTIME_DIR"

# Limit V8 heap to prevent unbounded growth on memory-constrained VMs.
# 160 MiB old-space — firebase-admin lazy-loads for the notification scheduler,
# so we need headroom above 128. V8 GC keeps RSS under ~220 MB.
export NODE_OPTIONS="${NODE_OPTIONS:+$NODE_OPTIONS }--max-old-space-size=160"

# Switch to nextjs user and run the server
exec su-exec nextjs:nodejs node server.js